#!/bin/sh

# Run Vignette (with runtime if present)
if which dotnet > /dev/null; then
  current_dir="$(pwd)"
  cd /usr/lib/vignette/
  env DOTNET_CLI_TELEMETRY_OPTOUT="${DOTNET_CLI_TELEMETRY_OPTOUT-1}" \
    SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0 \
    dotnet Vignette.dll
  cd "$current_dir"
else
  env DOTNET_CLI_TELEMETRY_OPTOUT="${DOTNET_CLI_TELEMETRY_OPTOUT-1}" \
    SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0 \
    Vignette
fi
